image:
  repository: kong/kong-gateway
  tag: "3.9"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: a50da17f0a.us.cp0.konghq.com:443
  cluster_server_name: a50da17f0a.us.cp0.konghq.com
  cluster_telemetry_endpoint: a50da17f0a.us.tp0.konghq.com:443
  cluster_telemetry_server_name: a50da17f0a.us.tp0.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  router_flavor: expressions
  tracing_instrumentations: all
  tracing_sampling_rate: 1.0
  log_level: debug
  untrusted_lua: "on"


ingressController:
  enabled: false
  installCRDs: false

resources:
  requests:
    cpu: 1
    memory: "2Gi"

proxy:
  enabled: true
  type: ClusterIP
    
#  annotations:
#   service.beta.kubernetes.io/aws-load-balancer-type: nlb

status:
  enabled: true
  http:
    enabled: true
    containerPort: 8100
    parameters: []


